---
micronaut:
  metrics:
    enabled: ${ENABLE_METRICS_EXPORT:`false`}
    export:
      prometheus:
        enabled: ${ENABLE_PROMETHEUS_EXPORT:`false`}
        descriptions: ${ENABLE_PROMETHEUS_DESCRIPTIONS:`true`}
      otlp:
        enabled: ${ENABLE_OTLP_EXPORT:`false`}
        url: ${OTLP_EXPORT_URL:}
        headers: ${OTLP_EXPORT_HEADERS:}
        step: ${OTLP_EXPORT_STEP:`PT1M`}
    binders:
      # Disable the built-in binders to reduce the number of metrics
      executor.enabled: false
      files.enabled: false
      jdbc.enabled: false
      jvm.enabled: false
      logback.enabled: false
      processor.enabled: false
      uptime.enabled: false
      web.enabled: false
  application:
    name: kuvasz
  openapi:
    additional:
      files: 'src/main/resources/swagger'
  security:
    redirect:
      forbidden:
        enabled: false
      unauthorized:
        enabled: false
      login-success: /
      login-failure: /login?error=true
      logout: /
    authentication: cookie
    endpoints:
      login:
        path: /auth/login
        enabled: true
      logout:
        enabled: true
        path: /auth/logout
        get-allowed: true
    enabled: ${ENABLE_AUTH:`true`}
    token:
      bearer:
        enabled: true
      generator:
        access-token:
          expiration: ${AUTH_MAX_AGE:`86400`}
      jwt:
        signatures:
          secret:
            generator:
              secret: ${random.uuid2}
        generator:
          refresh-token:
            enabled: false
    intercept-url-map:
      - pattern: /api/v1/health
        access: isAnonymous()
      - pattern: /api/v1/info
        access: isAnonymous()
      - pattern: /api/**
        access:
          - ROLE_API
      - pattern: /auth/login
        method: POST
        access: isAnonymous()
      - pattern: /**
        access: isAnonymous()
  router:
    static-resources:
      public:
        paths: classpath:public
        mapping: /public/**
  netty:
    event-loops:
      uptime-check:
        num-threads: 4
        prefer-native-transport: false
endpoints:
  all.path: /api/v1/
  health:
    enabled: true
    sensitive: false
  prometheus:
    sensitive: false # Otherwise it would be protected even if authentication is disabled
---
datasources:
  default:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: 'org.postgresql.Driver'
    schema: 'kuvasz'
    maximumPoolSize: 10
---
flyway:
  datasources:
    default:
      enabled: true
---
jackson:
  bean-introspection-module: false
  serialization-inclusion: always
  serialization:
    - WRITE_DATES_AS_TIMESTAMPS: false
---
jooq:
  datasources:
    default:
      sql-dialect: POSTGRES
---
logger:
  levels:
    io.netty.channel: ERROR
    io.netty.handler: ERROR
---
# Kuvasz specific configurations are starting here
app-config:
  event-data-retention-days: ${EVENT_DATA_RETENTION_DAYS:`365`}
  latency-data-retention-days: ${LATENCY_DATA_RETENTION_DAYS:`7`}
  log-event-handler: ${ENABLE_LOG_EVENT_HANDLER:`true`}
  language: ${APP_LANGUAGE:`en`}
---
admin-auth:
  username: ${ADMIN_USER}
  password: ${ADMIN_PASSWORD}
  api-key: ${ADMIN_API_KEY}
---
metrics-exports:
  uptime-status: ${ENABLE_UPTIME_STATUS_EXPORT:`false`}
  latest-latency: ${ENABLE_LATEST_LATENCY_EXPORT:`false`}
  ssl-status: ${ENABLE_SSL_STATUS_EXPORT:`false`}
  ssl-expiry: ${ENABLE_SSL_EXPIRY_EXPORT:`false`}
