openapi: 3.0.1
info:
  title: kuvasz
  version: latest
paths:
  /api/v1/health:
    get:
      tags:
        - Management operations
      summary: Health endpoint
      description: General health check endpoint
      operationId: health
      parameters: []
      responses:
        "200":
          description: Service is UP
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResult'
        "503":
          description: Service is DOWN
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResult'
components:
  schemas:
    HealthResult:
      type: object
      properties:
        status:
          type: string
          enum:
            - UP
            - DOWN
            - UNKNOWN
