---
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
  openapi:
    views.spec: 'swagger-ui.enabled=true'
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    enabled: true
    intercept-url-map:
      # Unfortunately it's only overridable, but not extendable, therefore we need to redefine the whole map here
      - pattern: /api/v1/health
        access: isAnonymous()
      - pattern: /api/v1/info
        access: isAnonymous()
      - pattern: /api/**
        access:
          - ROLE_API
      - pattern: /auth/login
        method: POST
        access: isAnonymous()
      - pattern: /**
        access: isAnonymous()
      ## Swagger-UI is only enabled in DEV
      - pattern: /swagger-ui/**
        access: isAnonymous()
      - pattern: /swagger/**
        access: isAnonymous()
    token:
      jwt:
        signatures:
          secret:
            generator:
              # Providing a hard-coded secret to prevent logouts in localdev env
              secret: cd961db8-54a1-4c09-b608-e528db09f74f
---
datasources:
  default:
    username: 'postgres'
    password: 'postgres'
---
admin-auth:
  username: user
  password: pass3j4hkhk23hk23k232hk3h232
  api-key: 3hjlkh23k2h3k2h3k2h3k2h3k2h3k2h3
---
smtp-config:
  host: ${SMTP_HOST:`sandbox.smtp.mailtrap.io`}
  port: ${SMTP_PORT:`465`}
---
logger:
  levels:
#    io.micronaut.http.client: TRACE
#    org.jooq: DEBUG
---
monitors:
  - name: test1
    url: https://demo.kuvasz-uptime.dev
    uptime-check-interval: 120
    enabled: false
    ssl-check-enabled: true
    request-method: HEAD
    latency-history-enabled: false
    force-no-cache: false
    follow-redirects: false
  - name: test2
    url: https://kuvasz-uptime.dev
    uptime-check-interval: 60
