services:
  postgres-16:
    image: postgres:16
    container_name: postgres16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: 'Europe/Vienna'
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  kuvasz:
    image: kuvaszmonitoring/kuvasz:latest
    mem_limit: 384M
    ports:
      - "8080:8080"
    environment:
      TZ: 'Europe/Vienna'
      DATABASE_HOST: postgres16
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      ENABLE_LOG_EVENT_HANDLER: 'true'
      UPTIME_DATA_RETENTION_DAYS: 365
      LATENCY_DATA_RETENTION_DAYS: 30
    volumes:
      - ./application-dev.yml:/config/kuvasz.yml
    depends_on:
      - postgres-16
