site_name: Kuvasz Uptime
site_url: https://kuvasz-uptime.dev
site_description: Kuvasz is an open-source, self-hosted uptime monitoring solution that provides comprehensive monitoring capabilities for websites and services.
repo_url: https://github.com/kuvasz-uptime/kuvasz
theme:
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    tag:
      min_ver: material/tag
  name: material
  logo: images/kuvasz-logo.webp
  favicon: images/favicon.png
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - announce.dismiss
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - redoc-tag
  - social
  - glightbox:
      skip_classes:
        - skip-lb
extra:
  tags:
    min_ver: Minimum version
hooks:
  - overrides/hooks/shortcodes.py
extra_css:
  - stylesheets/custom.css
nav:
  - Introduction: index.md
  - Getting Started:
      - Installation: setup/installation.md
      - Configure Kuvasz: setup/configuration.md
      - Integrations setup: setup/integrations.md
      - Managing monitors: setup/managing-monitors.md
      - Recipes & Examples: setup/examples.md
  - Features:
      - Uptime monitoring: features/uptime-monitoring.md
      - SSL monitoring: features/ssl-monitoring.md
      - Notifications: features/notifications.md
      - Web UI: features/ui.md
      - Flexibility: features/flexibility.md
      - Performance: features/performance.md
      - API: features/api.md
  - Localization: localization.md
  - API docs: api-doc.md
  - Changelog: changelog.md
  - Conventions: conventions.md
  - License: https://github.com/kuvasz-uptime/kuvasz/blob/main/LICENSE
  - Contributing: https://github.com/kuvasz-uptime/kuvasz/blob/main/CONTRIBUTING.md
  - Sponsoring: https://ko-fi.com/kuvasz
copyright: Copyright &copy; 2020 - 2025 Kuvasz Uptime
